### PR TITLE
adding EventBridge support

### PR DESCRIPTION
**Pull request by petertownsend**
Adding support for EventBridge

### CODE REVIEW

**Comment by Blind-Striker** [comment]
Hi @petertownsend are we sure that LocalStack supports EventBridge? I couldn't find it in their python client library?

[localstack/localstack-python-client](https://github.com/localstack/localstack-python-client)

**Comment by petertownsend** [comment]
> Hi @petertownsend are we sure that LocalStack supports EventBridge? I couldn't find it in their python client library?
> 
> [localstack/localstack-python-client](https://github.com/localstack/localstack-python-client)

Yes, it uses Cloudwatch Events

**Comment by Blind-Striker** [comment]
ok i think EventBridge is the new version of CloudWatch Event. Will merge your PR after i merge [v1.2.3.1](https://github.com/localstack-dotnet/localstack-dotnet-client/tree/v1.2.3.1) branch

**Comment by Blind-Striker** [comment]
The new version is released https://github.com/localstack-dotnet/localstack-dotnet-client/releases/tag/1.3.0

Thanks @petertownsend for your contribution.

**Pull request merged**
